eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: false  #alertive can disable the gate way regist in eurek
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/

server:
  port: 3000
  
spring:
  application:
    name: smc-gateway

zuul:
  routes:
    api-auth-service:
      path: /api/authenticate
      serviceId: SMC-AUTH-SERVICE
    smc-company-service:
      path: /**/company/**
      serviceId: SMC-COMPANY-SERVICE
    api-stock-service:
      path: /**/stock/**
      serviceId: SMC-STOCK-SERVICE
    api-upload-service:
      path: /**/upload/**
      serviceId: SMC-UPLOAD-SERVICE
ribbon:
  eureka:
    enabled: true