eureka:
  instance:
#    lease-expiration-duration-in-seconds: 60  #no need to set rexpiration for gateway.
    lease-renewal-interval-in-seconds: 5
  client:
    register-with-eureka: false #alertive can disable the gate way regist in eurek
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:3001/eureka/

server:
  port: 3000
  
spring:
  application:
    name: smc-gateway

zuul:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000  #default 10ms
    max-total-connections: 200  #default
    max-per-route-connections: 20  #default
    time-unit: MILLISECONDS  #default
    time-to-live: 30000
  sensitive-headers:    #keep empty to avoid missing Cookie, Authorization in header.
  routes:
    smc-company-service:
      path: /**/company/**
      serviceId: SMC-COMPANY-SERVICE
    api-stock-service:
      path: /**/stockprice/**
      serviceId: SMC-STOCK-SERVICE
    api-upload-service:
      path: /**/upload/**
      serviceId: SMC-UPLOAD-SERVICE
    api-auth-service:
      path: /**
#      path: /api/authenticate
#      path: /api/currentuser
      serviceId: SMC-AUTH-SERVICE
#ribbon:
#  ReadTimeout: 60000
#  eureka:
#    enabled: true